IncentiveTest/Models/Cliente.cs
using System;

namespace IncentiveTest.Models
{
    public class Cliente
    {
        public string Ciudad { get; set; }

        public int Codigo { get; set; }

        public string Direccion { get; set; }

        public bool Estado { get; set; }

        public DateTime FechaRegistro { get; set; }

        public string Nombre { get; set; }
    }
}

IncentiveTest/Controllers/IndexController.cs
using System.Web.Mvc;

using IncentiveTest.Methods;

namespace IncentiveTest.Controllers
{
    public class IndexController : Controller
    {
        // GET: Index
        public ActionResult Index()
        {
            string url = "http://www.incentive.cl:8004/Api/Clientes";
            var a = WebResponse.GetAllClients(url);
            return View(a);
        }

        public ActionResult Details(int id)
        {
            string url = "http://www.incentive.cl:8004/Api/Clientes?id=" + id;
            var model = WebResponse.GetCliente(url);
            return View(model);
        }
    }
}

IncentiveTest/Views/Index/Details.cshtml
@model IncentiveTest.Models.Cliente

<div>
    <h4>Cliente - @Model.Nombre</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Código
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Codigo)
        </dd>
        <dt>
            Nombre
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt>
            Dirección
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>
        <dt>
            Ciudad
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Ciudad)
        </dd>
        <dt>
            Fecha Registro
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FechaRegistro)
        </dd>
        <dt>
            Estado
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Volver", "Index")
</p>

IncentiveTest/Views/Index/Index.cshtml
@model IList<IncentiveTest.Models.Cliente>

@Html.Partial("~/Views/Partial/Modal.cshtml")

<table id="cliente" class="table">
    <tr>
        <th>
            Código
        </th>
        <th>
            Nombre
        </th>
        <th>
            Direccion
        </th>
        <th>
            Comuna
        </th>
        <th></th>
    </tr>
    @foreach (var cliente in Model)
    {
        <tr id="@cliente.Codigo.ToString()">
            <td>
                @Html.DisplayFor(model => cliente.Codigo)
            </td>
            <td>
                @Html.DisplayFor(model => cliente.Nombre)
            </td>
            <td>
                @Html.DisplayFor(model => cliente.Direccion)
            </td>
            <td>
                @Html.DisplayFor(model => cliente.Ciudad)
            </td>
            <td>
                @Html.ActionLink("Detail", "Details", new { id = cliente.Codigo.ToString() }) |
                <a id="Delete" href="javascript:void(0)">Delete</a>
            </td>
        </tr>
    }
</table>

IncentiveTest/Views/Partial/Modal.cshtml
<div id="modalConfirmacion" class="modal fade" role="dialog" data-backdrop="false" data-keyboard="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Advertencia</h4>
            </div>
            <div class="modal-body">
                <p>¿Está seguro que desea eliminar el registro?</p>
            </div>
            <div class="modal-footer">
                <button type="button" data-dismiss="modal" class="btn btn-primary" id="btnDeleteYes">Confirmar</button>
                <button type="button" class="btn btn-default" data-dismiss="modal" id="btnDeleteNo">Cancel</button>
            </div>
        </div>
    </div>
</div>

IncentiveTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Incentive Test</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css"/>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css"/>
    <script src="~/Scripts/jquery-1.12.4.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/script.js"></script>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <div class="col-md-6">
                <img src="/Content/Imagen/principal_logo.png" height="50" width="105">
            </div>
            <div class="col-md-6">@Html.ActionLink("Home", "Index", "Index", new { area = "" }, new { @class = "navbar-brand" })</div>
        </div>
    </div>
</div>

<div class="container body-content">
    @RenderBody()
</div>
</body>
</html>